### ISSUE TITLE
length estimate

### ISSUE THREAD

**Issue by madelynnblue** [jfreymuth/go-vorbis#1]
Thanks for this library. I have been waiting for something like this for a while so I could implement native ogg support in [moggio](mjibson/moggio). I happily moved to your package from a [cgo package](mccoyst/vorbis) and yours worked the [first try](https://github.com/mjibson/moggio/commit/d60f1afaf3450c987f0b555e6c4e30fd025c2094).

One feature that was added to that other package is a [length getter](https://godoc.org/github.com/mccoyst/vorbis#Length) that returns the song duration given its bytes (or a io.Reader, whatever). It's implemented by getting the total number of samples / the sample rate. Would it be possible to add a similar function or method to your package? I realize this may be an expensive function to call, and I could easily write one myself using a loop, but it may be useful if the package provided it.

**Comment by jfreymuth** [comment]
I've added a Length() function to ogg.Reader.
The implementation could still be made more efficient, but is it faster than decoding the entire file. I will do this properly when (if) I implement seeking.

**Comment by madelynnblue** [comment]
Thanks, works great.
